// import Vue from 'vue';
// import Router from 'vue-router';
import { domain, fromNow } from './filters';
import App from './components/App.vue';
import NewsView from './components/NewsView.vue';
import ItemView from './components/ItemView.vue';
import UserView from './components/UserView.vue';
var homeComponent=require('./home/Index.vue');
var passportComponent=require('./passport/Index.vue');
// install router
var Vue=require("vue");
var Router=require("vue-router");
Vue.use(Router);

// register filters globally
Vue.filter('fromNow', fromNow);
Vue.filter('domain', domain);

// routing
var router = new Router();

router.map({
  '/':{
       component:require("./passport/Index.vue")
        // subRoutes:{
        //     name:"passport",
        //     componet:require("./passport/components/PassPort.vue")
        // }
    },
  '/test':{
       name:"test",
       component:require("./test/Index.vue")
  },
  '/testHome': {
   name:"testHome",
    component: homeComponent,
      subRoutes:{
          "/problems":{
              name:"problems",
              component:require("./problem/Index.vue"),
              subRoutes:{
                  '/:page':{
                      name:"problemList",
                      component:require('./problem/components/ProblemList.vue')
                  },
                  '/addProblem':{
                      name:"problemAdd",
                      component:require('./problem/components/problemAdd.vue')
                  }
              }
          },
          "/papers":{
              name:"papers",
              component:require("./paper/Index.vue"),
              subRoutes:{
                  '/':{
                      name:"paperAuto",
                      component:require('./paper/components/PaperAutoGenerated.vue')
                  },
                  '/paperManGenerated':{
                      name:"paperMan",
                      component:require('./paper/components/PaperManGenerated.vue')
                  }
              }
          },
         "/users":{
             name:"users",
             component:require('./user/Index.vue'),
             subRoutes:{
                 '/':{
                     name:"usersList",
                     component:require("./user/components/UserList.vue")
                 }
             }
         }
      }
  },
  '/user/:id': {
    component: UserView
  },
  '/item/:id': {
    component: ItemView
  }
});

router.beforeEach(function () {
  window.scrollTo(0, 0)
});

router.redirect({
    '/testHome':'/testHome/problems/1'
});

var app=Vue.extend({
     // el:"body",
    
     data:function(){
        return {

        }
     },
     components:{
         'home':homeComponent,
         'passport':passportComponent
     },
     events:{
        'redirect':function (newVal) {
            if(newVal=="学生")
            {
                this.$route.router.go({name:'test',query:{role:newVal}});
            }else if(newVal=="教师")
            {
                this.$route.router.go({name:'testHome',query:{role:newVal}});
            }else if(newVal=="管理员"){
                this.$route.router.go({name:'testHome',query:{role:newVal}});
            }
        }
     },
     created:function(){
     }
})

router.start(app, 'body');router.start(app, 'body');